/**
 * Blackwood Pines - Objectives & Milestones Tracker
 * Contains 100+ distinct tracked survival goals, mission directives,
 * environmental milestones, and secret achievements.
 */

export type ObjectiveCategory =
  | 'STORY'
  | 'EXPLORATION'
  | 'SURVIVAL'
  | 'STEALTH'
  | 'SCAVENGING'
  | 'ENDURANCE';

export interface GameObjective {
  id: string;
  category: ObjectiveCategory;
  title: string;
  description: string;
  target: number;
  current: number;
  completed: boolean;
  reward?: string;
  secret?: boolean;
}

export const INITIAL_OBJECTIVES: GameObjective[] = [
  // =================== 1. STORY & MAIN DIRECTIVES (15) ===================
  {
    id: 'story_start',
    category: 'STORY',
    title: 'Stranded at North Trailhead',
    description: 'Survive the initial vehicle stall in the deep northern woods.',
    target: 1,
    current: 1,
    completed: true,
  },
  {
    id: 'story_truck_hood',
    category: 'STORY',
    title: 'Inspect Disabled Engine',
    description: 'Pop open the crashed pickup truck hood to assess mechanical damage.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_keycard',
    category: 'STORY',
    title: 'Retrieve Ranger Mortise Key',
    description: 'Find the heavy brass key hidden around the patrol truck or cabin perimeter.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_cabin_enter',
    category: 'STORY',
    title: 'Secure the Ranger Station',
    description: 'Unlock and enter the timber ranger outpost to find warmth and safety.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_radio_note',
    category: 'STORY',
    title: 'Inspect the Ham Radio Desk',
    description: 'Examine the communications desk and read the ranger frequency log.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_cctv_monitor',
    category: 'STORY',
    title: 'Review Trail Camera Feeds',
    description: 'Access the solar CCTV station inside the cabin to monitor beast movements.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_spark_plug_1',
    category: 'STORY',
    title: 'Locate Spark Plug #1',
    description: 'Scavenge a heavy-duty industrial spark plug from the forest shacks.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_spark_plug_2',
    category: 'STORY',
    title: 'Locate Spark Plug #2',
    description: 'Discover the second spark plug hidden near ancient stone monoliths.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_spark_plug_3',
    category: 'STORY',
    title: 'Locate Spark Plug #3',
    description: 'Retrieve the final spark plug from the old lumber mill workbench.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_fuel_can',
    category: 'STORY',
    title: 'Secure 5-Gallon Diesel Fuel',
    description: 'Find the red steel fuel container stored at the western logging camp.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_generator_pour',
    category: 'STORY',
    title: 'Fuel the Caterpillar Generator',
    description: 'Pour diesel into the fuel reservoir at the Southeast power shed.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_generator_plugs',
    category: 'STORY',
    title: 'Seat Industrial Ignition Plugs',
    description: 'Install all 3 spark plugs into the high-voltage generator engine block.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'story_generator_start',
    category: 'STORY',
    title: 'Crank the Recoil Starter',
    description: 'Yank the steel pull-cord to roar the industrial generator to life.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'story_floodlights_active',
    category: 'STORY',
    title: 'High-Voltage Illumination',
    description: 'Witness the forestry floodlight array ignite across the misty canopy.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'story_highway_escape',
    category: 'STORY',
    title: 'Disengage Highway Exit Gate',
    description: 'Sprint to the southern perimeter gate and escape the Blackwood forest.',
    target: 1,
    current: 0,
    completed: false,
  },

  // =================== 2. EXPLORATION & CARTOGRAPHY (20) ===================
  {
    id: 'explore_find_map',
    category: 'EXPLORATION',
    title: 'Surveyor Topographic Chart',
    description: 'Find the forestry trail map pinned to a surveyor board or cabin table.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_truck_wreck',
    category: 'EXPLORATION',
    title: 'Wreckage Site Recon',
    description: 'Explore within 10 meters of the northern crashed pickup truck.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_old_chimney',
    category: 'EXPLORATION',
    title: 'Hearth Stone Chimney',
    description: 'Visit the river rock hearth inside the cabin to warm your hands.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_stone_circle',
    category: 'EXPLORATION',
    title: 'Ancient Stone Monoliths',
    description: 'Discover the ancient megalithic rune circle deep within sector 4.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_logging_camp',
    category: 'EXPLORATION',
    title: 'Western Timber Mill',
    description: 'Navigate the muddy tracks to the abandoned logging outpost.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_generator_shed',
    category: 'EXPLORATION',
    title: 'High-Voltage Power Shed',
    description: 'Locate the corrugated steel shed housing the power equipment.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_south_gate',
    category: 'EXPLORATION',
    title: 'Highway Perimeter Gate',
    description: 'Reach the steel evacuation gate at the southern boundary.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_eastern_ridge',
    category: 'EXPLORATION',
    title: 'Eastern Granite Ridge',
    description: 'Trek along the eastern rocky bluff overlooking the foggy valley.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_western_swamp',
    category: 'EXPLORATION',
    title: 'Whispering Hollow',
    description: 'Venture into the dense pine hollow on the western perimeter.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_100',
    category: 'EXPLORATION',
    title: 'Trail Walker I',
    description: 'Travel 100 meters across the misty forest trails.',
    target: 100,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_250',
    category: 'EXPLORATION',
    title: 'Trail Walker II',
    description: 'Travel 250 meters through the wilderness.',
    target: 250,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_500',
    category: 'EXPLORATION',
    title: 'Forest Scout',
    description: 'Traverse 500 meters across rugged pine terrain.',
    target: 500,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_1000',
    category: 'EXPLORATION',
    title: 'Blackwood Pathfinder',
    description: 'Trek over 1,000 meters through the dense foggy wilderness.',
    target: 1000,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_2000',
    category: 'EXPLORATION',
    title: 'Iron Sole Hiker',
    description: 'Rack up 2,000 meters of nocturnal mountain navigation.',
    target: 2000,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dist_3500',
    category: 'EXPLORATION',
    title: 'Mountain Marathoner',
    description: 'Survive and cover 3,500 meters of hostile wooded territory.',
    target: 3500,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_cctv_all',
    category: 'EXPLORATION',
    title: 'Security Operator',
    description: 'Cycle through all 4 surveillance camera feeds on the CCTV monitor.',
    target: 4,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_lookout_view',
    category: 'EXPLORATION',
    title: 'Canopy Stargazer',
    description: 'Look straight up into the starry fog canopy for 5 consecutive seconds.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_cabin_porch',
    category: 'EXPLORATION',
    title: 'Under the Porch Lantern',
    description: 'Take shelter beneath the flickering kerosene lantern on the cabin porch.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_perimeter_fence',
    category: 'EXPLORATION',
    title: 'Boundary Surveyor',
    description: 'Patrol along the electrified chain-link fence lines.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'explore_dark_pines',
    category: 'EXPLORATION',
    title: 'Heart of Darkness',
    description: 'Venture more than 30 meters away from any structure or road.',
    target: 1,
    current: 0,
    completed: false,
  },

  // =================== 3. SURVIVAL & THERMAL VITALS (18) ===================
  {
    id: 'surv_body_temp_safe',
    category: 'SURVIVAL',
    title: 'Hypothermia Prevention',
    description: 'Keep your body core temperature above 75% for 3 continuous minutes.',
    target: 180,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_warm_by_hearth',
    category: 'SURVIVAL',
    title: 'Campfire Respite',
    description: 'Stand beside the glowing cabin hearth to raise body temperature to 100%.',
    target: 100,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_flare_warmth',
    category: 'SURVIVAL',
    title: 'Magnesium Heat',
    description: 'Warm yourself in the thermal radiance of an ignited road flare.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_shiver_survive',
    category: 'SURVIVAL',
    title: 'Teeth Chattering',
    description: 'Experience intense shivering from freezing temperatures and recover.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_frostbite_edge',
    category: 'SURVIVAL',
    title: 'On the Brink of Frostbite',
    description: 'Drop below 25% core temperature and successfully find heat in time.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_stamina_drain',
    category: 'SURVIVAL',
    title: 'Exhaustive Sprint',
    description: 'Completely exhaust your sprint stamina bar escaping danger.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_stamina_recover',
    category: 'SURVIVAL',
    title: 'Catch Your Breath',
    description: 'Fully recharge stamina from empty while crouching in silence.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_battery_change',
    category: 'SURVIVAL',
    title: 'Fresh Cells',
    description: 'Swap a drained flashlight battery with a fresh lithium cell.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_battery_change_3',
    category: 'SURVIVAL',
    title: 'Power Conservationist',
    description: 'Successfully reload your tactical flashlight 3 separate times.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_tap_flicker',
    category: 'SURVIVAL',
    title: 'Percussive Maintenance',
    description: 'Smack your flickering flashlight housing to restore the halogen beam.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_tap_flicker_5',
    category: 'SURVIVAL',
    title: 'Flashlight Mechanic',
    description: 'Fix the failing flashlight connection 5 times during fog surges.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_uv_mode',
    category: 'SURVIVAL',
    title: 'Ultraviolet Inspection',
    description: 'Switch the tactical light into UV blacklight inspection mode.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_uv_runes',
    category: 'SURVIVAL',
    title: 'Occult Cryptographer',
    description: 'Illuminate and reveal glowing occult runes with your UV light.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_dark_walk',
    category: 'SURVIVAL',
    title: 'Nyctophobia Master',
    description: 'Walk through the pitch-black forest for 60 seconds with lights off.',
    target: 60,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_storm_endure',
    category: 'SURVIVAL',
    title: 'Lightning Eye',
    description: 'Witness 3 sudden lightning strikes illuminating the misty trees.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_wind_gusts',
    category: 'SURVIVAL',
    title: 'Gale Resistance',
    description: 'Withstand 5 freezing mountain wind gusts without stopping.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_jump_obstacle',
    category: 'SURVIVAL',
    title: 'Agile Ranger',
    description: 'Leap over fallen logs or obstacles in the trail 10 times.',
    target: 10,
    current: 0,
    completed: false,
  },
  {
    id: 'surv_breath_condensation',
    category: 'SURVIVAL',
    title: 'Vapor Trails',
    description: 'Observe 20 clouds of freezing breath vapor in front of your face.',
    target: 20,
    current: 0,
    completed: false,
  },

  // =================== 4. STEALTH & STALKER EVASION (20) ===================
  {
    id: 'stealth_crouch_walk',
    category: 'STEALTH',
    title: 'Silent Footsteps',
    description: 'Crouch-walk for 50 meters to minimize acoustic footfall noise.',
    target: 50,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_crouch_150',
    category: 'STEALTH',
    title: 'Shadow Prowler',
    description: 'Cover 150 meters entirely in crouch mode.',
    target: 150,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_hold_breath_1',
    category: 'STEALTH',
    title: 'Deathly Silence',
    description: 'Hold your breath while the antlered creature is within 15 meters.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_hold_breath_5',
    category: 'STEALTH',
    title: 'Lung of Steel',
    description: 'Execute 5 successful breath holds during creature proximity alerts.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_hide_locker',
    category: 'STEALTH',
    title: 'Behind Grated Metal',
    description: 'Conceal yourself inside a ranger locker while the beast patrols past.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_hide_locker_3',
    category: 'STEALTH',
    title: 'Master of Lockers',
    description: 'Safely utilize locker concealment 3 separate times.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_lean_peek',
    category: 'STEALTH',
    title: 'Corner Surveillance',
    description: 'Lean left or right around doorframes to peek down hallways.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_throw_bottle_1',
    category: 'STEALTH',
    title: 'Shattered Diversion',
    description: 'Hurl a glass bottle into the dark to lure the stalker away.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_throw_bottle_3',
    category: 'STEALTH',
    title: 'Acoustic Decoy Specialist',
    description: 'Distract the beast using 3 glass distraction bottles.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_ignite_flare_1',
    category: 'STEALTH',
    title: 'Phosphorus Deterrent',
    description: 'Light an Orion road flare to ward off the shadow entity.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_ignite_flare_3',
    category: 'STEALTH',
    title: 'Pyrotechnic Shield',
    description: 'Deploy 3 emergency flares when cornered by the beast.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_evade_chase_1',
    category: 'STEALTH',
    title: 'Narrow Escape I',
    description: 'Break line of sight and successfully evade an active chase.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_evade_chase_3',
    category: 'STEALTH',
    title: 'Narrow Escape II',
    description: 'Escape 3 separate high-intensity predator pursuits.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_evade_chase_5',
    category: 'STEALTH',
    title: 'Untouchable Ranger',
    description: 'Survive 5 full creature pursuits without taking fatal damage.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_branch_avoid',
    category: 'STEALTH',
    title: 'Soft Step Specialist',
    description: 'Navigate trails for 2 minutes without snapping brittle pine branches.',
    target: 120,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_close_call',
    category: 'STEALTH',
    title: 'Whisper Distance',
    description: 'Allow the entity within 8 meters without triggering a full chase.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_dark_stalk',
    category: 'STEALTH',
    title: 'Ghost in the Fog',
    description: 'Pass the entity in the woods with your flashlight switched off.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_heartbeat_survive',
    category: 'STEALTH',
    title: 'Tachycardia',
    description: 'Endure rapid maximum heartbeat audio and survive the encounter.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_geiger_crack',
    category: 'STEALTH',
    title: 'Static Sensor Echo',
    description: 'Track the entity purely by monitoring radio receiver interference.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'stealth_no_flare_run',
    category: 'STEALTH',
    title: 'Frugal Evader',
    description: 'Reach Chapter 3 without igniting any defensive flares.',
    target: 1,
    current: 0,
    completed: false,
  },

  // =================== 5. RESOURCE SCAVENGING & LORE (15) ===================
  {
    id: 'scav_read_note_1',
    category: 'SCAVENGING',
    title: 'Survivor Log Entry I',
    description: 'Read the initial distress journal left on the cabin table.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_read_note_3',
    category: 'SCAVENGING',
    title: 'Investigative Archivist',
    description: 'Discover and read 3 field journals scattered throughout the woods.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_read_all_notes',
    category: 'SCAVENGING',
    title: 'Unraveling Blackwood',
    description: 'Locate and read all survivor field logs and ranger memos.',
    target: 7,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_find_battery_1',
    category: 'SCAVENGING',
    title: 'Power Cache I',
    description: 'Scavenge a spare battery pack from the forest workbenches.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_find_batteries_all',
    category: 'SCAVENGING',
    title: 'Master Scavenger: Cells',
    description: 'Scavenge 5 spare flashlight batteries in a single run.',
    target: 5,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_find_bottles_all',
    category: 'SCAVENGING',
    title: 'Glass Arsenal',
    description: 'Collect 4 glass diversion bottles hidden in shacks and camps.',
    target: 4,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_find_flares_all',
    category: 'SCAVENGING',
    title: 'Emergency Pyrotechnician',
    description: 'Find 3 emergency road flare packs across the forest perimeter.',
    target: 3,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_pickup_radio_tube',
    category: 'SCAVENGING',
    title: 'Vacuum Tube Cache',
    description: 'Locate the glass 12AX7 vacuum tube to repair the ham radio set.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_repair_radio',
    category: 'SCAVENGING',
    title: 'Distress Frequency',
    description: 'Install vacuum tube into ham radio receiver and hear the broadcast.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_truck_dashboard',
    category: 'SCAVENGING',
    title: 'Ranger Glove Box',
    description: 'Search the crashed truck dashboard for emergency supplies.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_logging_toolchest',
    category: 'SCAVENGING',
    title: 'Lumberjack Toolbox',
    description: 'Raid the heavy steel tool chest at the logging clearing.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_monolith_altar',
    category: 'SCAVENGING',
    title: 'Sacrificial Stone',
    description: 'Inspect the central stone slab inside the ancient monolith ring.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_generator_tank',
    category: 'SCAVENGING',
    title: 'Fuel Inspection',
    description: 'Check the fuel gauge on the Caterpillar industrial engine.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_full_pockets',
    category: 'SCAVENGING',
    title: 'Prepared for the Long Night',
    description: 'Hold at least 2 batteries, 2 bottles, and 2 flares simultaneously.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'scav_hoarder',
    category: 'SCAVENGING',
    title: 'Blackwood Hoarder',
    description: 'Collect a total of 12 distinct items across the map.',
    target: 12,
    current: 0,
    completed: false,
  },

  // =================== 6. ENDURANCE & SURVIVAL MILESTONES (15) ===================
  {
    id: 'endure_time_60s',
    category: 'ENDURANCE',
    title: 'First Minute Alive',
    description: 'Survive for 60 seconds after entering the Blackwood perimeter.',
    target: 60,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_180s',
    category: 'ENDURANCE',
    title: 'Three Minutes in Hell',
    description: 'Survive 3 minutes in the freezing foggy darkness.',
    target: 180,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_300s',
    category: 'ENDURANCE',
    title: 'Five Minute Veteran',
    description: 'Survive 5 minutes against the hunting beast.',
    target: 300,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_600s',
    category: 'ENDURANCE',
    title: 'Ten Minutes of Terror',
    description: 'Endure 10 minutes of nocturnal wilderness stalker combat.',
    target: 600,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_900s',
    category: 'ENDURANCE',
    title: 'Quarter Hour Sentinel',
    description: 'Survive for 15 solid minutes without perishing.',
    target: 900,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_1200s',
    category: 'ENDURANCE',
    title: 'Twenty Minute Master',
    description: 'Navigate and survive 20 minutes in the Blackwood woods.',
    target: 1200,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_1800s',
    category: 'ENDURANCE',
    title: 'Half-Hour Ironclad',
    description: 'Survive 30 minutes in hostile mountain territory.',
    target: 1800,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_2700s',
    category: 'ENDURANCE',
    title: 'The Long Dark (45 Min)',
    description: 'Maintain survival vitals for 45 full minutes.',
    target: 2700,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_time_3600s',
    category: 'ENDURANCE',
    title: 'Hour of Dawn (60 Min)',
    description: 'Survive one full hour of nightmare nocturnal hunting.',
    target: 3600,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_zero_death_ch1',
    category: 'ENDURANCE',
    title: 'Flawless Chapter I',
    description: 'Complete Chapter I without taking damage or dying.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_zero_death_ch2',
    category: 'ENDURANCE',
    title: 'Flawless Chapter II',
    description: 'Complete Chapter II without taking damage or dying.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_zero_death_ch3',
    category: 'ENDURANCE',
    title: 'Flawless Chapter III',
    description: 'Complete Chapter III without taking damage or dying.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_victory',
    category: 'ENDURANCE',
    title: 'Blackwood Survivor',
    description: 'Successfully escape through the forestry gate and win the game.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_nightmare_run',
    category: 'ENDURANCE',
    title: 'Nightmare Transcendence',
    description: 'Beat Blackwood Pines on Nightmare difficulty mode.',
    target: 1,
    current: 0,
    completed: false,
  },
  {
    id: 'endure_speedrun',
    category: 'ENDURANCE',
    title: 'Forestry Sprinter',
    description: 'Restore power and escape in under 8 minutes.',
    target: 480,
    current: 0,
    completed: false,
  },
];
